
 - name: Deploy App ABC
  hosts: abc-app
  vars:
    url_repo: https://github.com/karisaardelia/server1.git
    app_name : abc-app
    app_home: /opt/abc-app

  tasks:
  - name: Start NGINX Health Check
    include_role:
      name: deploy_app
