---
- name: Installing NGINX
  hosts: nginx-lb
  become: true
  gather_facts: true
  
  vars:
    - os_user: root
    - os_group: root
    - access_log_file: nginx.access
    - error_log_file: nginx.error
    - systemd_name: nginx
  roles:
    - install_nginx
