- name: Install python3
  apt:
    name: python3
    state: present

- name: install pip3
  apt:
    name: python3-pip
    state: present
    
- name: clone repo
  ansible.builtin.git:
    src: '{{url_repo}}'
    dest: '{{ app_home }}'

- name: install flask
  pip:
    name: flask
    
- name: create service configuration
  ansible.builtin.template:
    src: templates/app.service.j2
    dest: {{ service_home }}/{{ app_name }}.service
    force: yes
    group: "{{ os_group }}"
    owner: "{{ os_user }}"
    mode : 0644
    backup: yes
  register: service_config
    
- name: Restart service configuration
  systemd:
    name: "{{app_name}}"
    enabled: yes
    daemon_reload: yes
    state: restarted
  when: service_config.changed

- name: Check if service running
  systemd:
    name: "{{ app_name }}"
    enabled: yes
    daemon_reload: yes
    state: started
    masked: no
